default: &default
  adapter: mysql2
  encoding: utf8
  database: reactions
  pool: 5
  username: root
  password:

development:
  <<: *default

production:
  <<: *default
  database: <%= ENV['RDS_DB'] %>
  username: <%= ENV['RDS_USER'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host:     <%= ENV['RDS_ENDPOINT'] %>
  port:     <%= ENV['RDS_PORT'] %>
