# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96ee1a64c7be022679ecff12bd00b0401f245d1d21ed3257673605454ae3312cc5fa19a4f845262024abeb75f7799ddaa18cd62a476aed1d02470476d16d0f6

test:
  secret_key_base: 5ac6889b6d07aef5c4d1d987465862b16918d2b420be0b5fbac96d880385adf6cd687def5ae4b0e78fc3d85708ee7ebb6e69a8a114d4a71c4e825068d657d643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
